#!/usr/bin/env bash
# redirecting
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null
string_for_replacement="location /redirect_me {\n\treturn 301 https://www.example.com;\n}"
sudo sed -i "/server_name _;/a $string_for_replacement" /etc/nginx/sites-enabled/default
sudo service nginx restart
