#!/usr/bin/env bash
# Bash script that stops the 4-to_infinity_and_beyond process

# Find the process ID (PID) of the 4-to_infinity_and_beyond script
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
  # Send the SIGTERM signal to terminate the process
  kill "$pid"
  echo "Terminated"
else
  echo "Process not found"
fi

