#!/usr/bin/env bash
# This script is displaying "Best School" 6 times, 4th bad luck and 8th good luck
i=1
while [ $i -le 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
